version: 1.2
workflows:
   -  name: Dipcall
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/dipcall.wdl
   -  name: BUSCO
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/busco.wdl
   -  name: Quast
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/quast.wdl
   -  name: Meryl
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/meryl.wdl
   -  name: Merqury
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/merqury.wdl
   -  name: Asmgene
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/asmgene.wdl
   -  name: YakAsmStats
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak.wdl
   -  name: YakAsmStatsnoQV
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak_no_qv.wdl
   -  name: Mash
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/mash.wdl
   -  name: GreatLengths
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/great_lengths.wdl
   -  name: FullQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/full_qc.wdl
   -  name: StandardQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc.wdl
   -  name: StandardQCnoQV
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc_no_qv.wdl
   -  name: TrioHifiasmAssembly
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly.wdl
   -  name: YakNoStats
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/yak_no_stats.wdl
   -  name: Bwa
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/bwa.wdl
   -  name: LongReadAligner
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/long_read_aligner.wdl
   -  name: MergeSortedBams
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/merge_bams.wdl
   -  name: Asset
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/asset.wdl
   -  name: Bam2Paf
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/bam2paf.wdl
   -  name: BamCoverage
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/bam_coverage.wdl
   -  name: FitModelByCoverage
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/workflows/fit_model_by_coverage.wdl
   -  name: FitModelByCounts
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/fit_model.wdl
   -  name: ProbTable2Bed
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/prob_table2bed.wdl
   -  name: AssetBamInput
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/workflows/asset_bam_input.wdl
   -  name: AssetBamInputOntHiFi
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/workflows/asset_bam_input_ont_hifi.wdl
   -  name: AssetBamInputHiFi
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/workflows/asset_bam_input_hifi.wdl
   -  name: AssetBamInputOntHiFiBionano
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/workflows/asset_bam_input_ont_hifi_bionano.wdl
   -  name: BionanoAlignment
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/bionano.wdl
   -  name: FullAlignmentForAsset
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/workflows/full_alignment_for_asset.wdl
   -  name: DnaBrnn
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/dna_brnn.wdl
   -  name: AssetMerge
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/asset_merge.wdl
   -  name: AssetMergeLongRead
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/asset_merge_long_read.wdl
   -  name: MapBlocks
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/map_blocks.wdl
   -  name: Bed2Fasta
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/bed2fasta.wdl
   -  name: Asm2AsmAligner
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/asm2asm_aligner.wdl
   -  name: ProduceFai
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/produce_fai.wdl
   -  name: VariantCalling
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/variant_calling.wdl
   -  name: DownSampling
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/down_sampling.wdl
   -  name: ProjectBlocks
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/project_blocks.wdl
   -  name: ProjectBlocksMale
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/project_blocks_male.wdl
   -  name: ProjectBlocksFemale
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/project_blocks_female.wdl
   -  name: ProduceAutosomalBed 
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/produce_autosomal_bed.wdl
   -  name: ProduceSexBed
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/produce_sex_bed.wdl
   -  name: SubsetCoverage
      subclass: WDL
      primaryDescriptorPath: /asset/wdl/tasks/subset_coverage.wdl
